version: '3'

services:
  postgres-cdc:
    image: debezium/example-postgres:1.3
    container_name: postgres-cdc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432

  transaction-generator:
    image: tzolov/credit-card-transaction-generator:1.0.1-SNAPSHOT
    container_name: transaction-generator
    ports:
      - "8384:8384"
    expose:
      - "8384"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-cdc:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - server.port=8384
    depends_on:
      - postgres-cdc

  dataflow-cdc-app-import:
    image: springcloud/openjdk:2.0.0.RELEASE
    container_name: dataflow-cdc-app-import
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        ./wait-for-it.sh -t 180 dataflow-server:9393;
        wget -qO- 'http://dataflow-server:9393/apps/processor/fraud-detection/3.0.0-SNAPSHOT' --post-data='uri=docker:tzolov/fraud-detection-processor-kafka:3.0.0-SNAPSHOT&force=true';
        echo 'CDC and Fraud apps imported'"
